version:  '3.7'
services:
    apache:
        build: .docker/apache
        container_name: todo_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www/to_do_list
        depends_on:
          - php

    mysql:
        image: mysql:8
        container_name: todo_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo
            MYSQL_USER: todo
            MYSQL_PASSWORD: todo

    php:
        build: .docker/php
        container_name: todo_php
        volumes:
          - .:/var/www/to_do_list
        environment:
          - maildev_host=todo_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: todo_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql
            
    maildev:
        image: djfarrelly/maildev
        container_name: todo_maildev
        ports:
          - 8001:80        